In [1]:
import pandas as pd
import numpy as np
import time
import os
import zipfile
import pandas_gbq
import unidecode
from google.cloud import bigquery
import re

c:\Users\ana.sales_republica\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
diretorio = 'G:\\Drives compartilhados\\República.org\\4. Equipes\\Dados e Comunicação\\DADOS E CONHECIMENTO\\460 - Estudos e Infográficos\\20 - Sistema prisional\\bases de dados'

In [3]:
os.chdir(diretorio)

In [4]:
os.listdir(diretorio)

['15o-ciclo-base-de-dados-2023-2-semestre-1.csv',
 '3o-ciclo-base-de-dados-2017-2-semestre.csv',
 '5o-ciclo-base-de-dados-2018-2-semestre.csv',
 '7o-ciclo-base-de-dados-2019-2-semestre.csv',
 '11o-ciclo-base-de-dados-2021-2-semestre.csv',
 '17o-ciclo-base-de-dados-2024-2-semestre.csv',
 'sistema_prisional.ipynb',
 '13o-ciclo-base-de-dados-2022-2-semestre.csv',
 'notas.md',
 '1º semestre',
 'infopen_2014.csv',
 'infopen_2015.csv',
 '1o-ciclo-base-de-dados-2016-2-semestre.csv',
 '9o-ciclo-base-de-dados-2020-2-semestre (1).csv',
 '17o-ciclo-base-de-dados-2024-2-semestre - Copia.csv',
 'qtd_total_epor_1000_por_profissao_saude.csv',
 'consolidado_geral_pop_profissoes.csv',
 'cnes-assistentes-sociais-mil-habitantes-g0B7UJeVYo6Vk4w7y.csv',
 'pop_por_cor_total_pct.xlsx',
 'saude_profissoes_ano.xlsx',
 'areas_por_pop_ano.xlsx',
 'saude_fisica.xlsx',
 'saude_mental_ano.xlsx',
 'saude_2024_profissao.xlsx',
 'mental_pop.xlsx']

In [5]:
df16 = pd.read_csv('1o-ciclo-base-de-dados-2016-2-semestre.csv', encoding= 'utf8', sep=';')
df17 = pd.read_csv('3o-ciclo-base-de-dados-2017-2-semestre.csv', encoding= 'utf8', sep=';')
df18 = pd.read_csv('5o-ciclo-base-de-dados-2018-2-semestre.csv', encoding= 'utf8', sep=';')
df19 = pd.read_csv('7o-ciclo-base-de-dados-2019-2-semestre.csv', encoding= 'utf8', sep=';')
df20 = pd.read_csv('9o-ciclo-base-de-dados-2020-2-semestre (1).csv', encoding= 'utf8', sep=';')
df21 = pd.read_csv('11o-ciclo-base-de-dados-2021-2-semestre.csv', encoding= 'utf8', sep=';')
df22 = pd.read_csv('13o-ciclo-base-de-dados-2022-2-semestre.csv', encoding= 'utf8', sep=';')
df23 = pd.read_csv('15o-ciclo-base-de-dados-2023-2-semestre-1.csv', encoding= 'utf8', sep=';')
df24 = pd.read_csv('17o-ciclo-base-de-dados-2024-2-semestre.csv', encoding= 'utf8', sep=';')

C:\Users\ana.sales_republica\AppData\Local\Temp\ipykernel_3284\1506389750.py:2: DtypeWarning: Columns (128,130) have mixed types. Specify dtype option on import or set low_memory=False.
  df17 = pd.read_csv('3o-ciclo-base-de-dados-2017-2-semestre.csv', encoding= 'utf8', sep=';')
C:\Users\ana.sales_republica\AppData\Local\Temp\ipykernel_3284\1506389750.py:3: DtypeWarning: Columns (128,130) have mixed types. Specify dtype option on import or set low_memory=False.
  df18 = pd.read_csv('5o-ciclo-base-de-dados-2018-2-semestre.csv', encoding= 'utf8', sep=';')
C:\Users\ana.sales_republica\AppData\Local\Temp\ipykernel_3284\1506389750.py:4: DtypeWarning: Columns (128,130) have mixed types. Specify dtype option on import or set low_memory=False.
  df19 = pd.read_csv('7o-ciclo-base-de-dados-2019-2-semestre.csv', encoding= 'utf8', sep=';')
C:\Users\ana.sales_republica\AppData\Local\Temp\ipykernel_3284\1506389750.py:6: DtypeWarning: Columns (7,128,130,389) have mixed types. Specify dtype option on import or set low_memory=False.
  df21 = pd.read_csv('11o-ciclo-base-de-dados-2021-2-semestre.csv', encoding= 'utf8', sep=';')
C:\Users\ana.sales_republica\AppData\Local\Temp\ipykernel_3284\1506389750.py:9: DtypeWarning: Columns (7,36,118,121,128,130,147,389,395) have mixed types. Specify dtype option on import or set low_memory=False.
  df24 = pd.read_csv('17o-ciclo-base-de-dados-2024-2-semestre.csv', encoding= 'utf8', sep=';')

In [6]:
dfs = {
    2016: df16,
    2017: df17,
    2018: df18,
    2019: df19,
    2020: df20,
    2021: df21,
    2022: df22,
    2023: df23,
    2024: df24
}

In [7]:
df_todos = pd.concat(dfs, ignore_index=True)
df_todos = df_todos[df_todos['Tipo do Estabelecimento']=='Cela física']
df_todos

,ciclo,Ano,Referência,Tipo do Estabelecimento,Situação de Preenchimento,Nome do Estabelecimento,Situação do Estabelecimento,Outras Denominações,Endereço,Bairro,...,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Tonga | Masculino,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Tonga | Feminino,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Tonga | Total,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Tuvalu | Masculino,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Tuvalu | Feminino,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Tuvalu | Total,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Vanuatu | Masculino,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Vanuatu | Feminino,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Vanuatu | Total,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Outros países do continente Oceania | Total
1,1,2016,2016/2,Cela física,Validado,UNIDADE DE RECOLHIMENTO PROVISORIO,Ativo,NaN,Estrada do Barro Vermelho km 3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,2016,2016/2,Cela física,Validado,UNIDADE DE REGIME FECHADO FEMININO,Ativo,NaN,ESTRADA DO BARRO VERMELHO KM03,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,2016,2016/2,Cela física,Validado,UNIDADE DE REGIME FECHADO N1,Ativo,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,2016,2016/2,Cela física,Validado,UNIDADE DE REGIME FECHADO N2,Ativo,NaN,ESTRADA DO BARRO VERMELHO - KM 03,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1,2016,2016/2,Cela física,Validado,UNIDADE DE REGIME FECHADO N3,Ativo,NaN,ESTRADA DIAS MARTINS KM 05 S/N ATRÁS DO BOPE,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13666,17,2024,2024/2,Cela física,Validado,Penitenciária Federal em Brasília,Ativo,NaN,Rod DF-465 KM 01 - Complexo Penitenciário da P...,Setor Habitacional Jardim Botânico,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13667,17,2024,2024/2,Cela física,Validado,Penitenciária Federal em Campo Grande,Ativo,NaN,AVENIDA HENRIQUE BERTIN S/N JARDIM LOS ANGELES,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13668,17,2024,2024/2,Cela física,Validado,Penitenciária Federal em Catanduvas,Ativo,NaN,"Rodovia PR 471, Km 15, s/n",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13669,17,2024,2024/2,Cela física,Validado,Penitenciária Federal em Mossoró,Ativo,NaN,"RN 15, Km 13, Estrada Mossoró/Baraúnas - Mosso...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13670,17,2024,2024/2,Cela física,Validado,Penitenciária Federal em Porto Velho,Ativo,NaN,"SÍTIO DA BOA ESPERANÇA, LOTE 13, GLEBA 13 ""A"" ...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
col_masc = [
    '4.1 População prisional | Presos provisórios (sem condenação) | Justiça Estadual Masculino',
    '4.1 População prisional | Presos provisórios (sem condenação) | Justiça Federal Masculino',
    '4.1 População prisional | Presos provisórios (sem condenação) | Outros(Just. Trab., cível) Masculino',
    '4.1 População prisional | Presos sentenciados - regime fechado | Justiça Estadual Masculino',
    '4.1 População prisional | Presos sentenciados - regime fechado | Justiça Federal Masculino',
    '4.1 População prisional | Presos sentenciados - regime fechado | Outros(Just. Trab., cível) Masculino',
    '4.1 População prisional | Presos sentenciados - regime semiaberto | Justiça Estadual Masculino',
    '4.1 População prisional | Presos sentenciados - regime semiaberto | Justiça Federal Masculino',
    '4.1 População prisional | Presos sentenciados - regime semiaberto | Outros(Just. Trab., cível) Masculino',
    '4.1 População prisional | Presos sentenciados - regime aberto | Justiça Estadual Masculino',
    '4.1 População prisional | Presos sentenciados - regime aberto | Justiça Federal Masculino',
    '4.1 População prisional | Presos sentenciados - regime aberto | Outros(Just. Trab., cível) Masculino',
    '4.1 População prisional | Medida de segurança - internação | Justiça Estadual Masculino',
    '4.1 População prisional | Medida de segurança - internação | Justiça Federal Masculino',
    '4.1 População prisional | Medida de segurança - internação | Outros(Just. Trab., cível) Masculino',
    '4.1 População prisional | Medida de segurança - tratamento ambulatorial | Justiça Estadual Masculino',
    '4.1 População prisional | Medida de segurança - tratamento ambulatorial | Justiça Federal Masculino',
    '4.1 População prisional | Medida de segurança - tratamento ambulatorial | Outros(Just. Trab., cível) Masculino'
]

col_fem = [
    '4.1 População prisional | Presos provisórios (sem condenação) | Justiça Estadual Feminino',
    '4.1 População prisional | Presos provisórios (sem condenação) | Justiça Federal Feminino',
    '4.1 População prisional | Presos provisórios (sem condenação) | Outros(Just. Trab., cível) Feminino',
    '4.1 População prisional | Presos sentenciados - regime fechado | Justiça Estadual Feminino',
    '4.1 População prisional | Presos sentenciados - regime fechado | Justiça Federal Feminino',
    '4.1 População prisional | Presos sentenciados - regime fechado | Outros(Just. Trab., cível) Feminino',
    '4.1 População prisional | Presos sentenciados - regime semiaberto | Justiça Estadual Feminino',
    '4.1 População prisional | Presos sentenciados - regime semiaberto | Justiça Federal Feminino',
    '4.1 População prisional | Presos sentenciados - regime semiaberto | Outros(Just. Trab., cível) Feminino',
    '4.1 População prisional | Presos sentenciados - regime aberto | Justiça Estadual Feminino',
    '4.1 População prisional | Presos sentenciados - regime aberto | Justiça Federal Feminino',
    '4.1 População prisional | Presos sentenciados - regime aberto | Outros(Just. Trab., cível) Feminino',
    '4.1 População prisional | Medida de segurança - internação | Justiça Estadual Feminino',
    '4.1 População prisional | Medida de segurança - internação | Justiça Federal Feminino',
    '4.1 População prisional | Medida de segurança - internação | Outros(Just. Trab., cível) Feminino',
    '4.1 População prisional | Medida de segurança - tratamento ambulatorial | Justiça Estadual Feminino',
    '4.1 População prisional | Medida de segurança - tratamento ambulatorial | Justiça Federal Feminino',
    '4.1 População prisional | Medida de segurança - tratamento ambulatorial | Outros(Just. Trab., cível) Feminino'
]

In [ ]:
enf = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Total'].sum()
aux_enf= df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Total'].sum()
psi = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Total'].sum()
dent = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Total'].sum()
tec_dent = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Técnico/ auxiliar odontológico | Total'].sum()
assits = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Assistentes sociais | Total'].sum()
adv = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Advogados | Total'].sum()
med_geral = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos - clínicos gerais | Total'].sum()
med_gineco = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos – ginecologistas | Total'].sum()
med_psiq = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos – psiquiatras | Total'].sum()
med_outros = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos - outras especialidades | Total'].sum()
ped = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Pedagogos | Total'].sum()
prof= df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Professores | Total'].sum()
terapeuta_ocup = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Terapeuta/ terapeuta ocupacional | Total'].sum()

In [9]:
col_enfs = ['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Total',
             '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Total']

col_medicos_fisica = ['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos - clínicos gerais | Total',
                        '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos – ginecologistas | Total',
                       '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos - outras especialidades | Total']
                       
col_medicos_mental = ['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Total',
                    '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos – psiquiatras | Total',
                    '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Terapeuta/ terapeuta ocupacional | Total']
col_assits = ['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Assistentes sociais | Total']

col_pop = ['4.1 População prisional | Total']

In [10]:
resultados= []
dfs = [df16, df17, df18, df19, df20, df21, df22, df23, df24]
anos = list(range(2016, 2025))  # de 2016 a 2024

In [11]:
for df, ano in zip(dfs, anos):
    df = df[df['Tipo do Estabelecimento'] == 'Cela física'].copy()

    for col_group in [col_medicos_fisica, col_medicos_mental, col_enfs, col_assits, col_masc, col_fem]:
        for col in col_group:
            df[col] = pd.to_numeric(df[col], errors='coerce')

    # Soma populacional por sexo
    df['pop_masc'] = df[col_masc].sum(axis=1)
    df['pop_fem'] = df[col_fem].sum(axis=1)
    df['pop_total'] = df['pop_masc'] + df['pop_fem']
    
    df['total_medicos_fisica'] = df[col_medicos_fisica].sum(axis=1)
    df['total_medicos_mental'] = df[col_medicos_mental].sum(axis=1)
    df['total_enfs'] = df[col_enfs].sum(axis=1)
    df['total_assistentes_sociais'] = df[col_assits].sum(axis=1)
    df['ano'] = ano

    grupo = df.groupby(['UF', 'ano'])[
        ['total_medicos_fisica', 'total_medicos_mental', 'total_enfs', 'total_assistentes_sociais',
         'pop_masc', 'pop_fem', 'pop_total']
    ].sum().reset_index()

    resultados.append(grupo)

# DataFrame final unificado
saude_area_populacao_ano_uf = pd.concat(resultados, ignore_index=True)

In [12]:
saude_area_populacao_ano_uf

,UF,ano,total_medicos_fisica,total_medicos_mental,total_enfs,total_assistentes_sociais,pop_masc,pop_fem,pop_total
0,AC,2016,14.0,15.0,33.0,21.0,4955.0,330.0,5285.0
1,AL,2016,4.0,20.0,70.0,15.0,6700.0,411.0,7111.0
2,AM,2016,13.0,25.0,62.0,25.0,8510.0,1731.0,10241.0
3,AP,2016,3.0,21.0,15.0,11.0,2831.0,106.0,2937.0
4,BA,2016,29.0,84.0,173.0,50.0,13088.0,508.0,13596.0
...,...,...,...,...,...,...,...,...,...
238,RS,2024,71.0,161.0,158.0,167.0,34443.0,1714.0,36157.0
239,SC,2024,62.0,76.0,188.0,65.0,25901.0,1448.0,27349.0
240,SE,2024,13.0,24.0,104.0,21.0,5801.0,233.0,6034.0
241,SP,2024,173.0,204.0,791.0,196.0,196839.0,9145.0,205984.0
242,TO,2024,10.0,13.0,37.0,19.0,3734.0,154.0,3888.0

In [13]:
saude_area_populacao_ano_uf['medicos_fisica_por_1000'] = (
    saude_area_populacao_ano_uf['total_medicos_fisica'] /
    saude_area_populacao_ano_uf['pop_total']
) * 1000

saude_area_populacao_ano_uf['medicos_mental_por_1000'] = (
    saude_area_populacao_ano_uf['total_medicos_mental'] /
    saude_area_populacao_ano_uf['pop_total']
) * 1000

saude_area_populacao_ano_uf['total_enfs_por_1000'] = (
    saude_area_populacao_ano_uf['total_enfs'] /
    saude_area_populacao_ano_uf['pop_total']
) * 1000
saude_area_populacao_ano_uf['total_assists_por_1000'] = (
    saude_area_populacao_ano_uf['total_assistentes_sociais'] /
    saude_area_populacao_ano_uf['pop_total']
) * 1000
saude_area_populacao_ano_uf

,UF,ano,total_medicos_fisica,total_medicos_mental,total_enfs,total_assistentes_sociais,pop_masc,pop_fem,pop_total,medicos_fisica_por_1000,medicos_mental_por_1000,total_enfs_por_1000,total_assists_por_1000
0,AC,2016,14.0,15.0,33.0,21.0,4955.0,330.0,5285.0,2.649007,2.838221,6.244087,3.973510
1,AL,2016,4.0,20.0,70.0,15.0,6700.0,411.0,7111.0,0.562509,2.812544,9.843904,2.109408
2,AM,2016,13.0,25.0,62.0,25.0,8510.0,1731.0,10241.0,1.269407,2.441168,6.054096,2.441168
3,AP,2016,3.0,21.0,15.0,11.0,2831.0,106.0,2937.0,1.021450,7.150153,5.107252,3.745318
4,BA,2016,29.0,84.0,173.0,50.0,13088.0,508.0,13596.0,2.132980,6.178288,12.724331,3.677552
...,...,...,...,...,...,...,...,...,...,...,...,...,...
238,RS,2024,71.0,161.0,158.0,167.0,34443.0,1714.0,36157.0,1.963658,4.452803,4.369832,4.618746
239,SC,2024,62.0,76.0,188.0,65.0,25901.0,1448.0,27349.0,2.266993,2.778895,6.874109,2.376687
240,SE,2024,13.0,24.0,104.0,21.0,5801.0,233.0,6034.0,2.154458,3.977461,17.235665,3.480278
241,SP,2024,173.0,204.0,791.0,196.0,196839.0,9145.0,205984.0,0.839871,0.990368,3.840104,0.951530
242,TO,2024,10.0,13.0,37.0,19.0,3734.0,154.0,3888.0,2.572016,3.343621,9.516461,4.886831

In [14]:
total_enfs_pop = saude_area_populacao_ano_uf[['ano','UF','total_enfs', 'pop_total', 'total_enfs_por_1000']]
total_enfs_pop

      ano  UF  total_enfs  pop_total  total_enfs_por_1000
0    2016  AC        33.0     5285.0             6.244087
1    2016  AL        70.0     7111.0             9.843904
2    2016  AM        62.0    10241.0             6.054096
3    2016  AP        15.0     2937.0             5.107252
4    2016  BA       173.0    13596.0            12.724331
..    ...  ..         ...        ...                  ...
238  2024  RS       158.0    36157.0             4.369832
239  2024  SC       188.0    27349.0             6.874109
240  2024  SE       104.0     6034.0            17.235665
241  2024  SP       791.0   205984.0             3.840104
242  2024  TO        37.0     3888.0             9.516461

[243 rows x 5 columns]

In [15]:
total_enfs_pop['profissao'] = 'Enfermeiros, técnicos e auxiliares da enfermagem'

C:\Users\ana.sales_republica\AppData\Local\Temp\ipykernel_3284\983763041.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  total_enfs_pop['profissao'] = 'Enfermeiros, técnicos e auxiliares da enfermagem'

In [16]:
total_enfs_pop.columns

Index(['ano', 'UF', 'total_enfs', 'pop_total', 'total_enfs_por_1000',
       'profissao'],
      dtype='object')

In [17]:
total_enfs_pop = total_enfs_pop[['ano', 'UF', 'profissao', 'total_enfs', 'pop_total',
       'total_enfs_por_1000']]
total_enfs_pop

,ano,UF,profissao,total_enfs,pop_total,total_enfs_por_1000
0,2016,AC,"Enfermeiros, técnicos e auxiliares da enfermagem",33.0,5285.0,6.244087
1,2016,AL,"Enfermeiros, técnicos e auxiliares da enfermagem",70.0,7111.0,9.843904
2,2016,AM,"Enfermeiros, técnicos e auxiliares da enfermagem",62.0,10241.0,6.054096
3,2016,AP,"Enfermeiros, técnicos e auxiliares da enfermagem",15.0,2937.0,5.107252
4,2016,BA,"Enfermeiros, técnicos e auxiliares da enfermagem",173.0,13596.0,12.724331
...,...,...,...,...,...,...
238,2024,RS,"Enfermeiros, técnicos e auxiliares da enfermagem",158.0,36157.0,4.369832
239,2024,SC,"Enfermeiros, técnicos e auxiliares da enfermagem",188.0,27349.0,6.874109
240,2024,SE,"Enfermeiros, técnicos e auxiliares da enfermagem",104.0,6034.0,17.235665
241,2024,SP,"Enfermeiros, técnicos e auxiliares da enfermagem",791.0,205984.0,3.840104
242,2024,TO,"Enfermeiros, técnicos e auxiliares da enfermagem",37.0,3888.0,9.516461

In [18]:
total_enfs_pop = total_enfs_pop.rename(
                                            columns={'UF':'sigla_uf'                                  
                                            })
total_enfs_pop

,ano,sigla_uf,profissao,total_enfs,pop_total,total_enfs_por_1000
0,2016,AC,"Enfermeiros, técnicos e auxiliares da enfermagem",33.0,5285.0,6.244087
1,2016,AL,"Enfermeiros, técnicos e auxiliares da enfermagem",70.0,7111.0,9.843904
2,2016,AM,"Enfermeiros, técnicos e auxiliares da enfermagem",62.0,10241.0,6.054096
3,2016,AP,"Enfermeiros, técnicos e auxiliares da enfermagem",15.0,2937.0,5.107252
4,2016,BA,"Enfermeiros, técnicos e auxiliares da enfermagem",173.0,13596.0,12.724331
...,...,...,...,...,...,...
238,2024,RS,"Enfermeiros, técnicos e auxiliares da enfermagem",158.0,36157.0,4.369832
239,2024,SC,"Enfermeiros, técnicos e auxiliares da enfermagem",188.0,27349.0,6.874109
240,2024,SE,"Enfermeiros, técnicos e auxiliares da enfermagem",104.0,6034.0,17.235665
241,2024,SP,"Enfermeiros, técnicos e auxiliares da enfermagem",791.0,205984.0,3.840104
242,2024,TO,"Enfermeiros, técnicos e auxiliares da enfermagem",37.0,3888.0,9.516461

In [19]:
total_enfs_pop['total_enfs_por_1000']= total_enfs_pop['total_enfs_por_1000'].round(2)
total_enfs_pop

,ano,sigla_uf,profissao,total_enfs,pop_total,total_enfs_por_1000
0,2016,AC,"Enfermeiros, técnicos e auxiliares da enfermagem",33.0,5285.0,6.24
1,2016,AL,"Enfermeiros, técnicos e auxiliares da enfermagem",70.0,7111.0,9.84
2,2016,AM,"Enfermeiros, técnicos e auxiliares da enfermagem",62.0,10241.0,6.05
3,2016,AP,"Enfermeiros, técnicos e auxiliares da enfermagem",15.0,2937.0,5.11
4,2016,BA,"Enfermeiros, técnicos e auxiliares da enfermagem",173.0,13596.0,12.72
...,...,...,...,...,...,...
238,2024,RS,"Enfermeiros, técnicos e auxiliares da enfermagem",158.0,36157.0,4.37
239,2024,SC,"Enfermeiros, técnicos e auxiliares da enfermagem",188.0,27349.0,6.87
240,2024,SE,"Enfermeiros, técnicos e auxiliares da enfermagem",104.0,6034.0,17.24
241,2024,SP,"Enfermeiros, técnicos e auxiliares da enfermagem",791.0,205984.0,3.84
242,2024,TO,"Enfermeiros, técnicos e auxiliares da enfermagem",37.0,3888.0,9.52

In [24]:
total_enfs_pop[total_enfs_pop['ano']==2024]['total_enfs'].sum()

4592.0

In [28]:
total_enfs_pop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 243 entries, 0 to 242
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ano                  243 non-null    int64
 1   sigla_uf             243 non-null    object
 2   profissao            243 non-null    object
 3   total_enfs           243 non-null    float64
 4   pop_total            243 non-null    float64
 5   total_enfs_por_1000  243 non-null    float64
dtypes: float64(3), int64(1), object(2)
memory usage: 11.5+ KB

In [39]:
total_enfs_pop[total_enfs_pop['ano']==2024].sort_values(by='total_enfs_por_1000', ascending=False)

,ano,sigla_uf,profissao,total_enfs,pop_total,total_enfs_por_1000
217,2024,AL,"Enfermeiros, técnicos e auxiliares da enfermagem",131.0,5240.0,25.00
236,2024,RO,"Enfermeiros, técnicos e auxiliares da enfermagem",161.0,7466.0,21.56
220,2024,BA,"Enfermeiros, técnicos e auxiliares da enfermagem",283.0,13721.0,20.63
225,2024,MA,"Enfermeiros, técnicos e auxiliares da enfermagem",226.0,11743.0,19.25
240,2024,SE,"Enfermeiros, técnicos e auxiliares da enfermagem",104.0,6034.0,17.24
229,2024,PA,"Enfermeiros, técnicos e auxiliares da enfermagem",236.0,15498.0,15.23
232,2024,PI,"Enfermeiros, técnicos e auxiliares da enfermagem",97.0,7198.0,13.48
218,2024,AM,"Enfermeiros, técnicos e auxiliares da enfermagem",67.0,5111.0,13.11
237,2024,RR,"Enfermeiros, técnicos e auxiliares da enfermagem",41.0,3258.0,12.58
242,2024,TO,"Enfermeiros, técnicos e auxiliares da enfermagem",37.0,3888.0,9.52
234,2024,RJ,"Enfermeiros, técnicos e auxiliares da enfermagem",428.0,46115.0,9.28
235,2024,RN,"Enfermeiros, técnicos e auxiliares da enfermagem",69.0,7499.0,9.20
226,2024,MG,"Enfermeiros, técnicos e auxiliares da enfermagem",539.0,66282.0,8.13
224,2024,GO,"Enfermeiros, técnicos e auxiliares da enfermagem",139.0,18489.0,7.52
228,2024,MT,"Enfermeiros, técnicos e auxiliares da enfermagem",100.0,13735.0,7.28
239,2024,SC,"Enfermeiros, técnicos e auxiliares da enfermagem",188.0,27349.0,6.87
219,2024,AP,"Enfermeiros, técnicos e auxiliares da enfermagem",21.0,3257.0,6.45
223,2024,ES,"Enfermeiros, técnicos e auxiliares da enfermagem",145.0,24117.0,6.01
227,2024,MS,"Enfermeiros, técnicos e auxiliares da enfermagem",89.0,16662.0,5.34
221,2024,CE,"Enfermeiros, técnicos e auxiliares da enfermagem",119.0,22296.0,5.34
231,2024,PE,"Enfermeiros, técnicos e auxiliares da enfermagem",144.0,28983.0,4.97
230,2024,PB,"Enfermeiros, técnicos e auxiliares da enfermagem",58.0,12410.0,4.67
238,2024,RS,"Enfermeiros, técnicos e auxiliares da enfermagem",158.0,36157.0,4.37
233,2024,PR,"Enfermeiros, técnicos e auxiliares da enfermagem",158.0,40699.0,3.88
241,2024,SP,"Enfermeiros, técnicos e auxiliares da enfermagem",791.0,205984.0,3.84
222,2024,DF,"Enfermeiros, técnicos e auxiliares da enfermagem",50.0,16200.0,3.09
216,2024,AC,"Enfermeiros, técnicos e auxiliares da enfermagem",13.0,5401.0,2.41

In [23]:
client = bigquery.Client()
dataset_ref = client.dataset('perfil_remuneracao')

In [26]:

schema=[bigquery.SchemaField('ano','INTEGER',description='Ano de referencia'),
 bigquery.SchemaField('sigla_uf','STRING',description='Sigla da Unidade da Federação'),
 bigquery.SchemaField('profissao','STRING',description='Profissional'),
 bigquery.SchemaField('total_enfs','FLOAT',description='Quantidade de enfermeiros, tecnicos e auxiliares da enfermagem'),
 bigquery.SchemaField('pop_total','FLOAT',description='Total da população prisional'),
 bigquery.SchemaField('total_enfs_por_1000','FLOAT',description='Taxa de profissionais da enfermagem por 1000 presos')
 ]

In [27]:
table_ref = dataset_ref.table('SENAPPEN_profissionais_enfermagem_mil_presos') 
job_config = bigquery.LoadJobConfig(schema=schema)
job = client.load_table_from_dataframe(total_enfs_pop, table_ref, job_config=job_config)
job.result()

LoadJob<project=repositoriodedadosgpsp, location=US, id=591458af-d408-403c-9352-b5a73234e603>