# Dependências

In [2]:
# Install required Google Cloud packages (commented out as these are typically one-time setup commands)
#!pip install gcloud
#!gcloud auth application-default login

# Import necessary Python libraries
import pandas as pd                # Data manipulation and analysis
import numpy as np                 # Numerical computing
import time                        # Time-related functions
import os                          # Operating system interfaces
import pandas_gbq                  # Pandas integration with BigQuery
from google.cloud import bigquery  # BigQuery client library
import glob                        # File path pattern matching
import openpyxl                    # Excel file handling
import csv                         # CSV file handling

c:\Users\ana.sales_republica\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

# Tratamento

In [3]:
diretorio = 'G:\\Drives compartilhados\\República.org\\02. Áreas\\Dados e Conhecimento\\415 - Repositório de Dados\\Repositório Local\\PNAD'

In [4]:
os.chdir(diretorio)

In [6]:
os.listdir(diretorio)

['2025', '2024', 'pnad_indicadores_serie_2016_2025.xlsx']

In [12]:
df = pd.read_excel('pnad_indicadores_serie_2016_2025.xlsx', sheet_name='indicador_07')
df

,ano,sexo,cor,freq,freq_se,freq_cv,prop,prop_se,prop_cv
0,2016,Homem,Branca,150918.139490,10656.621934,0.070612,0.626129,0.023250,0.037132
1,2016,Homem,Negra,88488.282113,6581.831728,0.074381,0.367120,0.023747,0.064683
2,2016,Homem,Outra,1627.043379,1003.422568,0.616715,0.006750,0.004173,0.618160
3,2016,Mulher,Branca,96823.103556,6999.153516,0.072288,0.635953,0.027328,0.042971
4,2016,Mulher,Negra,54586.277753,5276.553342,0.096664,0.358533,0.027473,0.076626
5,2016,Mulher,Outra,839.384713,601.358131,0.716427,0.005513,0.003947,0.715850
6,2017,Homem,Branca,135176.129989,9617.558389,0.071148,0.612900,0.026614,0.043422
7,2017,Homem,Negra,83407.190296,7279.403718,0.087275,0.378175,0.026250,0.069411
8,2017,Homem,Outra,1968.226236,938.558342,0.476855,0.008924,0.004279,0.479442
9,2017,Mulher,Branca,92900.173183,8048.158848,0.086632,0.654076,0.028633,0.043776
10,2017,Mulher,Negra,45759.911270,4749.077605,0.103782,0.322179,0.027595,0.085652
11,2017,Mulher,Outra,3372.617830,1730.690102,0.513159,0.023745,0.012271,0.516781
12,2018,Homem,Branca,135591.849236,11176.845257,0.082430,0.575836,0.028461,0.049426
13,2018,Homem,Negra,98993.409376,6944.928582,0.070155,0.420408,0.028387,0.067522
14,2018,Homem,Outra,884.374725,486.114226,0.549670,0.003756,0.002045,0.544460
15,2018,Mulher,Branca,93430.116883,8023.014960,0.085872,0.632086,0.029744,0.047056
16,2018,Mulher,Negra,53972.367662,5015.008868,0.092918,0.365141,0.029869,0.081802
17,2018,Mulher,Outra,409.754993,279.827753,0.682915,0.002772,0.001868,0.673919
18,2019,Homem,Branca,130061.921119,10172.388463,0.078212,0.615953,0.027700,0.044972
19,2019,Homem,Negra,78116.812750,6252.461682,0.080040,0.369949,0.026766,0.072351
20,2019,Homem,Outra,2976.746780,1928.528634,0.647865,0.014097,0.009220,0.654046
21,2019,Mulher,Branca,106459.583863,9103.144939,0.085508,0.632708,0.030770,0.048632
22,2019,Mulher,Negra,60627.278514,5972.549730,0.098513,0.360319,0.030430,0.084452
23,2019,Mulher,Outra,1173.229398,838.246262,0.714478,0.006973,0.004870,0.698408
24,2020,Homem,Branca,92502.871804,8319.654441,0.089939,0.466108,0.045850,0.098367
25,2020,Homem,Negra,101830.552411,16095.509849,0.158062,0.513109,0.046808,0.091223
26,2020,Homem,Outra,4124.553851,3336.082219,0.808835,0.020783,0.016767,0.806766
27,2020,Mulher,Branca,91420.684274,8445.684152,0.092383,0.661802,0.030004,0.045336
28,2020,Mulher,Negra,45551.515291,4432.515519,0.097308,0.329751,0.029428,0.089244
29,2020,Mulher,Outra,1166.854683,1027.700985,0.880745,0.008447,0.007368,0.872237
30,2021,Homem,Branca,83734.333666,9708.501262,0.115944,0.481056,0.052889,0.109943
31,2021,Homem,Negra,80204.534173,13740.979486,0.171324,0.460777,0.052461,0.113854
32,2021,Homem,Outra,10124.631812,7820.962008,0.772469,0.058166,0.042562,0.731731
33,2021,Mulher,Branca,79577.693758,11303.190272,0.142040,0.663140,0.042513,0.064108
34,2021,Mulher,Negra,38436.993613,5301.409446,0.137925,0.320305,0.042300,0.132062
35,2021,Mulher,Outra,1986.679913,1509.423912,0.759772,0.016555,0.012180,0.735704
36,2022,Homem,Branca,105396.010111,9297.525153,0.088215,0.575079,0.033878,0.058910
37,2022,Homem,Negra,76009.014750,7998.881031,0.105236,0.414733,0.034625,0.083488
38,2022,Homem,Outra,1867.228019,1096.289086,0.587121,0.010188,0.006009,0.589795
39,2022,Mulher,Branca,63759.149537,7072.008445,0.110918,0.616279,0.041030,0.066576
40,2022,Mulher,Negra,37767.173437,4828.360641,0.127845,0.365047,0.040749,0.111627
41,2022,Mulher,Outra,1931.997437,1460.602609,0.756006,0.018674,0.014146,0.757528
42,2023,Homem,Branca,88316.257341,7513.594408,0.085076,0.532589,0.029270,0.054958
43,2023,Homem,Negra,74204.428361,6613.240856,0.089122,0.447488,0.029488,0.065896
44,2023,Homem,Outra,3303.627479,2387.720724,0.722757,0.019922,0.014035,0.704481
45,2023,Mulher,Branca,73721.197789,7553.981783,0.102467,0.587861,0.037647,0.064041
46,2023,Mulher,Negra,49255.469219,5996.293475,0.121739,0.392768,0.036791,0.093670
47,2023,Mulher,Outra,2429.204294,2236.076005,0.920497,0.019371,0.017544,0.905678
48,2024,Homem,Branca,106974.783587,10382.578535,0.097056,0.588463,0.033915,0.057634
49,2024,Homem,Negra,72186.303832,6836.213322,0.094702,0.397093,0.034147,0.085992
50,2024,Homem,Outra,2625.781575,1647.593364,0.627468,0.014444,0.008925,0.617891
51,2024,Mulher,Branca,71083.821453,6873.758861,0.096699,0.591152,0.035441,0.059953
52,2024,Mulher,Negra,47657.997900,5761.324943,0.120889,0.396337,0.034838,0.087900
53,2024,Mulher,Outra,1504.452713,815.271064,0.541905,0.012511,0.006814,0.544657
54,2025,Homem,Branca,117232.379321,10147.994388,0.086563,0.568832,0.032579,0.057274
55,2025,Homem,Negra,79384.052346,8015.287879,0.100968,0.385185,0.031087,0.080708
56,2025,Homem,Outra,9476.857937,4822.497992,0.508871,0.045983,0.021997,0.478373
57,2025,Mulher,Branca,81820.774382,8590.873359,0.104996,0.596173,0.033264,0.055795
58,2025,Mulher,Negra,52769.723561,5426.328650,0.102830,0.384497,0.033112,0.086117
59,2025,Mulher,Outra,2652.943913,1536.239978,0.579070,0.019330,0.011198,0.579313

In [10]:
df1 = pd.read_excel('G:\\Drives compartilhados\\República.org\\4. Equipes\\Dados e Comunicação\\DADOS E CONHECIMENTO\\415 - Repositório de Dados\\Repositório Local\\PNAD\\2024\\pnad_indicadores_output_v2.xlsx', sheet_name='Dados7')
df1

      cor    sexo            sum  prop         cv
0  Branca   Homem  106974.783587  58.8   5.539487
1  Branca  Mulher   71083.821453  59.1   8.336432
2   Negra   Homem   72186.303832  39.7   6.251243
3   Negra  Mulher   47657.997900  39.6   9.468591
4   Outra   Homem    2625.781575   1.4  33.100077
5   Outra  Mulher    1504.452713   1.3  57.770890

In [11]:
df1['ano'] = 2024
df1["sum"] = df1["sum"].round().astype("Int64")
df1 = df1.drop(columns=['cv'])
df1 = df1.rename(columns= {'sum':'quantidade_vinculos', 'cor':'cor_raca','sexo':'genero'}) 
df1 = df1[['ano', 'cor_raca', 'genero','quantidade_vinculos', 'prop']]              
df1

    ano cor_raca  genero  quantidade_vinculos  prop
0  2024   Branca   Homem               106975  58.8
1  2024   Branca  Mulher                71084  59.1
2  2024    Negra   Homem                72186  39.7
3  2024    Negra  Mulher                47658  39.6
4  2024    Outra   Homem                 2626   1.4
5  2024    Outra  Mulher                 1504   1.3

In [16]:
df = (
    df.groupby(["ano", "genero", "cor_raca"], as_index=False)
       .agg({"quantidade_vinculos": "sum"})
)

# calcular total por ano
df["total_ano"] = (
    df.groupby("ano")["quantidade_vinculos"].transform("sum")
)

# calcular proporção correta
df["prop_genero_cor_ano"] = (
    df["quantidade_vinculos"] / df["total_ano"]
) * 100

df.head()

    ano  genero cor_raca  quantidade_vinculos  total_ano  prop_genero_cor_ano
0  2025   Homem   Branca              1145904    3372556            33.977316
1  2025   Homem    Negra               832824    3372556            24.694149
2  2025   Homem    Outra                38980    3372556               1.1558
3  2025  Mulher   Branca               850997    3372556            25.232998
4  2025  Mulher    Negra               486384    3372556            14.421821

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ano                  6 non-null      int64
 1   genero               6 non-null      object
 2   cor_raca             6 non-null      object
 3   quantidade_vinculos  6 non-null      Int64
 4   total_ano            6 non-null      Int64
 5   prop_genero_cor_ano  6 non-null      Float64
dtypes: Float64(1), Int64(2), int64(1), object(2)
memory usage: 438.0+ bytes

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ano                  6 non-null      int64
 1   genero               6 non-null      object
 2   cor_raca             6 non-null      object
 3   quantidade_vinculos  6 non-null      Int64
 4   total_ano            6 non-null      Int64
 5   prop_genero_cor_ano  6 non-null      Float64
dtypes: Float64(1), Int64(2), int64(1), object(2)
memory usage: 438.0+ bytes

In [14]:
df_merged= pd.merge(df, df1, on=['ano', 'cor_raca', 'genero', 'quantidade_vinculos', 'prop'], how='outer')
df_merged

     ano cor_raca  genero  quantidade_vinculos   prop
0   2024   Branca   Homem               106975  58.80
1   2024   Branca  Mulher                71084  59.10
2   2024    Negra   Homem                72186  39.70
3   2024    Negra  Mulher                47658  39.60
4   2024    Outra   Homem                 2626   1.40
5   2024    Outra  Mulher                 1504   1.30
6   2025   Branca   Homem               117232  34.15
7   2025   Branca  Mulher                81821  23.83
8   2025    Negra   Homem                79384  23.12
9   2025    Negra  Mulher                52770  15.37
10  2025    Outra   Homem                 9477   2.76
11  2025    Outra  Mulher                 2653   0.77

# Upload

In [15]:
client = bigquery.Client(project='repositoriodedadosgpsp')

In [17]:
schema = [bigquery.SchemaField('ano', 'INTEGER', description= 'Ano de referência da observação'),
          bigquery.SchemaField('cor_raca', 'STRING', description= 'Raça/cor autodeclarado ou não'),
          bigquery.SchemaField('genero', 'STRING', description= 'Gênero autodeclarado ou não'),         
          bigquery.SchemaField('quantidade_vinculos', 'INTEGER', description= 'Número total de vinculos observados'),
          bigquery.SchemaField('prop', 'FLOAT', description= 'Proporção de vínculos em relação ao total naquele ano'),
          ]

dataset_ref = client.dataset('cargos_lideranca')

table_ref = dataset_ref.table('PNAD_vinculos_lideranca_genero_cor') 
job_config = bigquery.LoadJobConfig(schema=schema)
job = client.load_table_from_dataframe(df_merged, table_ref, job_config=job_config)
job.result()

LoadJob<project=repositoriodedadosgpsp, location=US, id=7fbe4e0f-6c07-48f1-ab1b-d55d2efa67fe>