In [ ]:
# Install required Google Cloud packages (commented out as these are typically one-time setup commands)
!pip install gcloud
!gcloud auth application-default login

In [1]:
import pandas as pd                # Data manipulation and analysis
import numpy as np                 # Numerical computing
import time                        # Time-related functions
import os                          # Operating system interfaces
import pandas_gbq                  # Pandas integration with BigQuery
from google.cloud import bigquery  # BigQuery client library
import glob                        # File path pattern matching
import openpyxl                    # Excel file handling
import csv                         # CSV file handling
import re

c:\Users\ana.sales_republica\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

# Tratamento

In [2]:
diretorio = 'G:\\Drives compartilhados\\República.org\\02. Áreas\\Dados e Conhecimento\\415 - Repositório de Dados\\Repositório Local\\PNAD'

In [3]:
os.chdir(diretorio)

In [4]:
os.listdir(diretorio)

['2025', '2024', 'pnad_indicadores_serie_2016_2025.xlsx']

Quantidade e porcentagem de pessoas que trabalham no setor público por raça e gênero em posição de liderança

In [16]:
df = pd.read_excel('pnad_indicadores_serie_2016_2025.xlsx', sheet_name='indicador_07')
df["freq"] = df["freq"].round().astype("Int64")
df["prop"] = (df["prop"] * 100).round(2)
df = df.drop(columns=['freq_se', 'freq_cv','prop_se', 'prop_cv'])
df = df.rename(columns= {'freq':'quantidade_vinculos', 'sexo':'genero','cor':'cor_raca'})   
df = df[['ano','genero','cor_raca','quantidade_vinculos']]              
df.head(6)

    ano  genero cor_raca  quantidade_vinculos
0  2016   Homem   Branca               150918
1  2016   Homem    Negra                88488
2  2016   Homem    Outra                 1627
3  2016  Mulher   Branca                96823
4  2016  Mulher    Negra                54586
5  2016  Mulher    Outra                  839

In [23]:
df_genero = (
    df.groupby(["ano", "genero"], as_index=False)
      .agg({"quantidade_vinculos": "sum"})
)

# calcular proporção dentro do ano
df_genero["prop_genero_ano"] = (
    df_genero["quantidade_vinculos"] /
    df_genero.groupby("ano")["quantidade_vinculos"].transform("sum")
) * 100

df_genero.head()

    ano  genero  quantidade_vinculos  prop_genero_ano
0  2016   Homem               241033        61.287731
1  2016  Mulher               152248        38.712269
2  2017   Homem               220551         60.82756
3  2017  Mulher               142033         39.17244
4  2018   Homem               235469        61.435083

In [34]:
df_cor = (
    df.groupby(["ano", "genero", "cor_raca"], as_index=False)
       .agg({"quantidade_vinculos": "sum"})
)

# calcular total por ano
df_cor["total_ano"] = (
    df_cor.groupby("ano")["quantidade_vinculos"].transform("sum")
)

# calcular proporção correta
df_cor["prop_genero_cor_ano"] = (
    df_cor["quantidade_vinculos"] / df_cor["total_ano"]
) * 100

df_cor.head(60)

,ano,genero,cor_raca,quantidade_vinculos,total_ano,prop_genero_cor_ano
0,2016,Feminino,Branca,96823,393281,24.619293
1,2016,Feminino,Negra,54586,393281,13.879643
2,2016,Feminino,Outra,839,393281,0.213333
3,2016,Masculino,Branca,150918,393281,38.374089
4,2016,Masculino,Negra,88488,393281,22.499943
5,2016,Masculino,Outra,1627,393281,0.413699
6,2017,Feminino,Branca,92900,362584,25.621649
7,2017,Feminino,Negra,45760,362584,12.620524
8,2017,Feminino,Outra,3373,362584,0.930267
9,2017,Masculino,Branca,135176,362584,37.281292
10,2017,Masculino,Negra,83407,362584,23.003497
11,2017,Masculino,Outra,1968,362584,0.542771
12,2018,Feminino,Branca,93430,383281,24.376371
13,2018,Feminino,Negra,53972,383281,14.081575
14,2018,Feminino,Outra,410,383281,0.106971
15,2018,Masculino,Branca,135592,383281,35.376656
16,2018,Masculino,Negra,98993,383281,25.827787
17,2018,Masculino,Outra,884,383281,0.23064
18,2019,Feminino,Branca,106460,379416,28.058912
19,2019,Feminino,Negra,60627,379416,15.979031
20,2019,Feminino,Outra,1173,379416,0.309159
21,2019,Masculino,Branca,130062,379416,34.279524
22,2019,Masculino,Negra,78117,379416,20.588747
23,2019,Masculino,Outra,2977,379416,0.784627
24,2020,Feminino,Branca,91421,336599,27.160211
25,2020,Feminino,Negra,45552,336599,13.533017
26,2020,Feminino,Outra,1167,336599,0.346703
27,2020,Masculino,Branca,92503,336599,27.481662
28,2020,Masculino,Negra,101831,336599,30.252912
29,2020,Masculino,Outra,4125,336599,1.225494
30,2021,Feminino,Branca,79578,294066,27.061272
31,2021,Feminino,Negra,38437,294066,13.070875
32,2021,Feminino,Outra,1987,294066,0.675699
33,2021,Masculino,Branca,83734,294066,28.47456
34,2021,Masculino,Negra,80205,294066,27.274489
35,2021,Masculino,Outra,10125,294066,3.443105
36,2022,Feminino,Branca,63759,286730,22.236599
37,2022,Feminino,Negra,37767,286730,13.171625
38,2022,Feminino,Outra,1932,286730,0.673805
39,2022,Masculino,Branca,105396,286730,36.757926
40,2022,Masculino,Negra,76009,286730,26.508911
41,2022,Masculino,Outra,1867,286730,0.651135
42,2023,Feminino,Branca,73721,291229,25.313757
43,2023,Feminino,Negra,49255,291229,16.912807
44,2023,Feminino,Outra,2429,291229,0.834052
45,2023,Masculino,Branca,88316,291229,30.325277
46,2023,Masculino,Negra,74204,291229,25.479605
47,2023,Masculino,Outra,3304,291229,1.134502
48,2024,Feminino,Branca,71084,302033,23.535177
49,2024,Feminino,Negra,47658,302033,15.77907
50,2024,Feminino,Outra,1504,302033,0.497959
51,2024,Masculino,Branca,106975,302033,35.418315
52,2024,Masculino,Negra,72186,302033,23.900037
53,2024,Masculino,Outra,2626,302033,0.869441
54,2025,Feminino,Branca,81821,343337,23.831105
55,2025,Feminino,Negra,52770,343337,15.369739
56,2025,Feminino,Outra,2653,343337,0.77271
57,2025,Masculino,Branca,117232,343337,34.144878
58,2025,Masculino,Negra,79384,343337,23.121306
59,2025,Masculino,Outra,9477,343337,2.760262

In [24]:
def transformar(nome):
    nome =  re.sub("Homem", "Masculino", nome)
    nome = re.sub("Mulher", "Feminino", nome)
    return nome

In [25]:
df['genero'] = df['genero'].apply(transformar)
df['genero'].unique()

array(['Masculino', 'Feminino'], dtype=object)

In [26]:
df

,ano,genero,cor_raca,quantidade_vinculos,prop_genero_cor_ano,total_ano
0,2016,Masculino,Branca,150918,38.374089,393281
1,2016,Masculino,Negra,88488,22.499943,393281
2,2016,Masculino,Outra,1627,0.413699,393281
3,2016,Feminino,Branca,96823,24.619293,393281
4,2016,Feminino,Negra,54586,13.879643,393281
5,2016,Feminino,Outra,839,0.213333,393281
6,2017,Masculino,Branca,135176,37.281292,362584
7,2017,Masculino,Negra,83407,23.003497,362584
8,2017,Masculino,Outra,1968,0.542771,362584
9,2017,Feminino,Branca,92900,25.621649,362584
10,2017,Feminino,Negra,45760,12.620524,362584
11,2017,Feminino,Outra,3373,0.930267,362584
12,2018,Masculino,Branca,135592,35.376656,383281
13,2018,Masculino,Negra,98993,25.827787,383281
14,2018,Masculino,Outra,884,0.23064,383281
15,2018,Feminino,Branca,93430,24.376371,383281
16,2018,Feminino,Negra,53972,14.081575,383281
17,2018,Feminino,Outra,410,0.106971,383281
18,2019,Masculino,Branca,130062,34.279524,379416
19,2019,Masculino,Negra,78117,20.588747,379416
20,2019,Masculino,Outra,2977,0.784627,379416
21,2019,Feminino,Branca,106460,28.058912,379416
22,2019,Feminino,Negra,60627,15.979031,379416
23,2019,Feminino,Outra,1173,0.309159,379416
24,2020,Masculino,Branca,92503,27.481662,336599
25,2020,Masculino,Negra,101831,30.252912,336599
26,2020,Masculino,Outra,4125,1.225494,336599
27,2020,Feminino,Branca,91421,27.160211,336599
28,2020,Feminino,Negra,45552,13.533017,336599
29,2020,Feminino,Outra,1167,0.346703,336599
30,2021,Masculino,Branca,83734,28.47456,294066
31,2021,Masculino,Negra,80205,27.274489,294066
32,2021,Masculino,Outra,10125,3.443105,294066
33,2021,Feminino,Branca,79578,27.061272,294066
34,2021,Feminino,Negra,38437,13.070875,294066
35,2021,Feminino,Outra,1987,0.675699,294066
36,2022,Masculino,Branca,105396,36.757926,286730
37,2022,Masculino,Negra,76009,26.508911,286730
38,2022,Masculino,Outra,1867,0.651135,286730
39,2022,Feminino,Branca,63759,22.236599,286730
40,2022,Feminino,Negra,37767,13.171625,286730
41,2022,Feminino,Outra,1932,0.673805,286730
42,2023,Masculino,Branca,88316,30.325277,291229
43,2023,Masculino,Negra,74204,25.479605,291229
44,2023,Masculino,Outra,3304,1.134502,291229
45,2023,Feminino,Branca,73721,25.313757,291229
46,2023,Feminino,Negra,49255,16.912807,291229
47,2023,Feminino,Outra,2429,0.834052,291229
48,2024,Masculino,Branca,106975,35.418315,302033
49,2024,Masculino,Negra,72186,23.900037,302033
50,2024,Masculino,Outra,2626,0.869441,302033
51,2024,Feminino,Branca,71084,23.535177,302033
52,2024,Feminino,Negra,47658,15.77907,302033
53,2024,Feminino,Outra,1504,0.497959,302033
54,2025,Masculino,Branca,117232,34.144878,343337
55,2025,Masculino,Negra,79384,23.121306,343337
56,2025,Masculino,Outra,9477,2.760262,343337
57,2025,Feminino,Branca,81821,23.831105,343337
58,2025,Feminino,Negra,52770,15.369739,343337
59,2025,Feminino,Outra,2653,0.77271,343337

# Upload

In [15]:
client = bigquery.Client(project='repositoriodedadosgpsp')

In [22]:
schema = [bigquery.SchemaField('ano', 'INTEGER', description= 'Ano de referência da observação'),
          bigquery.SchemaField('genero', 'STRING', description= 'Gênero autodeclarado ou não'),         
          bigquery.SchemaField('quantidade_vinculos', 'INTEGER', description= 'Número total de vinculos observados'),
          bigquery.SchemaField('prop', 'FLOAT', description= 'Proporção de vínculos em relação ao total naquele ano'),
          ]

dataset_ref = client.dataset('perfil_remuneracao')

table_ref = dataset_ref.table('PNAD_vinculos_genero') 
job_config = bigquery.LoadJobConfig(schema=schema)
job = client.load_table_from_dataframe(df, table_ref, job_config=job_config)
job.result()

LoadJob<project=repositoriodedadosgpsp, location=US, id=d47fae60-c2a2-494c-9d0b-6249358d8b9b>